### ISSUE TITLE
Question CS12800RA4101 aarch64

### ISSUE THREAD

**Issue by thomtomdup** [Chipsee/industrial-pi#3]
Hello.
Have you plan to update to Raspberry Pi OS 64-bit ?
Thank you.
Regards.

**Comment by thomtomdup** [comment]
Hello.
You don't plan to plan for arm64-bit compatibility?
Thank you.
Regards

**Comment by Liu-Xiaoqiang** [comment]
There is no prebuilt image yet, but you can reference follow driver and compile it by your self. you can only use kernel 5.10.92-v8+, If you use other kernel, you should do some modification.
https://github.com/Chipsee/industrial-pi/tree/5.10.92-v8+-beta

**Comment by thomtomdup** [comment]
Hello.
Escuse me for the delay.
i tried to run install from the branch https://github.com/Chipsee/industrial-pi/tree/5.10.92-v8+-beta But when i run make install i have an error : 

```
Unpacking raspberrypi-kernel-headers (1:1.20220120-1) over (1:1.20220120-1) ...
Setting up raspberrypi-kernel-headers (1:1.20220120-1) ...
make[1]: Entering directory '/home/pi/industrial-pi/gt9xx'
make -C /lib/modules/5.10.63-v8+/build M=`pwd` modules
make[2]: Entering directory '/home/pi/industrial-pi/gt9xx'
make[2]: *** /lib/modules/5.10.63-v8+/build: No such file or directory.  Stop.
make[2]: Leaving directory '/home/pi/industrial-pi/gt9xx'
make[1]: *** [Makefile:21: compile] Error 2
make[1]: Leaving directory '/home/pi/industrial-pi/gt9xx'
make: *** [Makefile:32: install] Error 2
```

Can you please help me ? :) 

Thank you, 
Regards.

**Comment by thomtomdup** [comment]
Hello.

I solved it by download and install 2022-01-28-raspios-bullseye-arm64 image.

`https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64.zip
`

I have 2 CS12800RA101. 1 work good after install but the other have buzzer noise during long time with blink of led 2 times every second and nothing on screen. I tried to redo  install but the issue is still there. I tried also to clone the one that works on the second one but the issue still there.

Thank you,
Regards.

**Comment by Liu-Xiaoqiang** [comment]
Cool.

**Comment by thomtomdup** [comment]
Hello.
Not cool really because just 1 work but the other not.
Do you know what is the issue and how to solve it ?

**Comment by Liu-Xiaoqiang** [comment]
There is one script to detect the hardware as our released system support all chipsee industrial-pi products (not support AIO-CM4-156), the buzzer will work when this system to detect CS12800RA101 and AIO-CM4-101, it's normal, you need just to wait some time, maybe 5 minutes, if the time is large then 5 minutes, there should have other issue. the system recognise wrong hardware. There is one file to record the detect process, /boot/chipseeinit_resize.log, you can share to help check.

**Comment by thomtomdup** [comment]
Hello.
I tried to wait 5 min ( i waited 20 min ) but the issue still here.
I will send you the chipseeinit_resize.log file when i will be more available.
Thank you.
Regards.

**Comment by Liu-Xiaoqiang** [comment]
We had released kernel driver for aarch64, you can checkout to test.
https://github.com/Chipsee/industrial-pi/tree/5.15.61
